### ISSUE TITLE
Update the INSTALL script to make New Relic work...

### ISSUE THREAD

**Issue by treyau21** [540co/ads-bpa#196]
Otherwise, you get the following:

```
New Relic for Node.js halted startup due to an error:
Error: Invalid license key, please contact support@newrelic.com
    at StreamSink.parser [as callback] (/Users/treywhite/Documents/dev/18f/ads-bpa/server/node_modules/newrelic/lib/collector/parse-response.js:81:25)
    at StreamSink.end (/Users/treywhite/Documents/dev/18f/ads-bpa/server/node_modules/newrelic/lib/util/stream-sink.js:43:8)
    at IncomingMessage.onend (_stream_readable.js:502:10)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

**Comment by killerbgt** [comment]
Removing newrelic.  This should not be a required dependency.  We'll install server side.
